import type { Metadata } from 'next'
import { VT323 } from 'next/font/google'
import './globals.css'
import Nav from '@/components/nav'
import { cn } from '@/lib/utils'

const font = VT323({ subsets: ['latin'], weight: ['400'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={cn(font.className, 'max-w-screen-md mx-auto')}>
        <Nav />
        <main>{children}</main>
      </body>
    </html>
  )
}
